#BIANCA TOLEDO
# DUE 3/6/17
#CLIENT SIDE OF APPLICATION
from socket import *
serverName = 'ns1.biola.edu'
serverPort = 12000
clientSocket = socket(AF_INET, SOCK_STREAM) #CREATES CLIENT SOCKET USING THE FIRST PARAMETER INDICATING THE UNDERLYING NETWORK USING IPv4. SECOND PARAMETER INDICATES THAT THE SOCKET IS OF TYPE SOCK_STREAM(TCP)
clientSocket.connect((serverName,serverPort)) #ESTABLISHES CONNECTION BETWEEN CLIENT AND SERVER
sentence = input(‘Input lowercase sentence:’) #TAKES IN SENTENCE FROM USER AND GATHERS CHARACTERS UNTIL CARRIAGE RETURN
clientSocket.send(sentence) #SENDS SENTENCE THROUGHT THE CLIENT INTO THE TCP CONNECTION
modifiedSentence = clientSocket.recv(1024) #PLACES STRING IN modifiedSentence UNTIL RETURN CHARACTER
print (‘From Server:’, modifiedSentence) #OUTPUTS
clientSocket.close() #CLOSES TCP CONNECTION BETWEEN CLIENT AND SERVER